import 'dart:convert';

import 'package:estudesemfronteiras/Entity/category.dart';

List<Courses> coursesFromJson(String str) =>
    List<Courses>.from(json.decode(str).map((x) => Courses.fromMap(x)));

class Courses {
  var id;
  var title;
  var course_id;
  var sagah;
  var category_id;
  var subcategoria_id;
  var type;
  var name;
  var name_sagah;
  var description;
  var canonical;
  var meta_description;
  var redirecionamento_301;
  var redirecionamento_302;
  var orig_price;
  var price;
  var installments;
  var installments_price;
  var objectives;
  var themes;
  var authors;
  var target_public;
  var methodology;
  var workload;
  var number_lessons;
  var orig_category;
  var site_id;
  var site_name;
  var access_time;
  var photo;
  var highlight;
  var highlight_workload;
  var promo;
  var promo_international;
  var trash;
  var outside;
  var vinculos;
  var promo_de;
  var promo_por;
  var promo_prev;
  var promo_limited;
  var promo_limited_international;
  var esconder;
  var pasta;
  var livro_texto;
  var descricao_rodape;
  var prm_produto_id;
  var category;

  Courses({
    required this.id,
    required this.course_id,
    required this.sagah,
    required this.category_id,
    required this.subcategoria_id,
    required this.type,
    required this.name,
    required this.name_sagah,
    required this.description,
    required this.canonical,
    required this.meta_description,
    required this.title,
    required this.redirecionamento_301,
    required this.redirecionamento_302,
    required this.orig_price,
    required this.price,
    required this.installments,
    required this.installments_price,
    required this.objectives,
    required this.themes,
    required this.authors,
    required this.target_public,
    required this.methodology,
    required this.workload,
    required this.number_lessons,
    required this.orig_category,
    required this.site_id,
    required this.site_name,
    required this.access_time,
    required this.photo,
    required this.highlight,
    required this.highlight_workload,
    required this.promo,
    required this.promo_international,
    required this.trash,
    required this.outside,
    required this.vinculos,
    required this.promo_de,
    required this.promo_por,
    required this.promo_prev,
    required this.promo_limited,
    required this.promo_limited_international,
    required this.esconder,
    required this.pasta,
    required this.livro_texto,
    required this.descricao_rodape,
    required this.prm_produto_id,
    this.category,
  });

  factory Courses.fromMap(Map<String, dynamic> json) => Courses(
    id: json['id'],
    course_id: json['course_id'],
    sagah: json['sagah'],
    category_id: json['category_id'],
    subcategoria_id: json['subcategoria_id'],
    type: json['type'],
    name: json['name'],
    name_sagah: json['name_sagah'],
    description: json['description'],
    canonical: json['canonical'],
    meta_description: json['meta_description'],
    title: json['title'],
    redirecionamento_301: json['redirecionamento_301'],
    redirecionamento_302: json['redirecionamento_302'],
    orig_price: json['orig_price'],
    price: json['price'],
    installments: json['installments'],
    installments_price: json['nstallments_price'],
    objectives: json['objectives'],
    themes: json['themes'],
    authors: json['authors'],
    target_public: json['target_public'],
    methodology: json['methodology'],
    workload: json['workload'],
    number_lessons: json['number_lessons'],
    orig_category: json['orig_category'],
    site_id: json['site_id'],
    site_name: json['site_name'],
    access_time: json['access_time'],
    photo: json['photo'],
    highlight: json['highlight'],
    highlight_workload: json['highlight_workload'],
    promo: json['promo'],
    promo_international: json['promo_international'],
    trash: json['trash'],
    outside: json['outside'],
    vinculos: json['vinculos'],
    promo_de: json['promo_de'],
    promo_por: json['promo_por'],
    promo_prev: json['promo_prev'],
    promo_limited: json['promo_limited'],
    promo_limited_international: json['promo_limited_international'],
    esconder: json['econder'],
    pasta: json['pasta'],
    livro_texto: json['livro_texto'],
    descricao_rodape: json['descricao_rodape'],
    prm_produto_id: json['prm_produto_id'],
    category: json['category']
  );
}